# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_handler(object):
    def setupUi(self, handler):
        handler.setObjectName("handler")
        handler.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(handler)
        self.centralwidget.setStyleSheet("QFrame#main_frame {\n"
"background-color: rgb(73, 52, 127);\n"
"\n"
"}\n"
"\n"
"QFrame#topMenu {\n"
"background-color:rgba(17, 0, 52, 150);\n"
"border-bottom:2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QLabel#seller{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QFrame#leftMenu {\n"
"background-color:rgb(17, 0, 52);\n"
"border-right:2px solid#000\n"
"}\n"
"\n"
"QFrame#rightMenu {\n"
"background-color:rgb(17, 0, 52);\n"
"border-left:2px solid#000\n"
"}\n"
"\n"
"QLabel#version{\n"
"color: rgba(132, 132, 132, 100);\n"
"}\n"
"\n"
"QLabel#appName{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton#btnAdd{\n"
"background-color:rgba(94, 62, 127, 200);\n"
"border-top-left-radius:11px;\n"
"border-bottom-left-radius:11px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover#btnAdd{\n"
"background-color:rgb(119, 78, 170);\n"
"}\n"
"\n"
"QPushButton:pressed#btnAdd{\n"
"background-color:rgb(63, 41, 90);\n"
"}\n"
"\n"
"QPushButton#btnSell{\n"
"background-color:rgba(94, 62, 127, 200);\n"
"border-top-right-radius:11px;\n"
"border-bottom-right-radius:11px;\n"
"}\n"
"\n"
"QPushButton:hover#btnSell{\n"
"background-color:rgb(119, 78, 170);\n"
"}\n"
"\n"
"QPushButton:pressed#btnSell{\n"
"background-color:rgb(63, 41, 90);\n"
"}\n"
"\n"
"QPushButton#btnClose{\n"
"background-color:transparent;\n"
"}\n"
"\n"
"QPushButton:hover#btnClose{\n"
"border:2px solid rgb(255, 0, 0);\n"
"border-radius:10px\n"
"}\n"
"\n"
"QPushButton:pressed#btnClose{\n"
"border:2px solid rgb(95, 0, 0);\n"
"}\n"
"\n"
"QPushButton#btnRefresh{\n"
"background-color:transparent;\n"
"}\n"
"\n"
"QPushButton:hover#btnRefresh{\n"
"border:2px solid rgb(95, 211, 141);\n"
"border-radius:11px\n"
"}\n"
"\n"
"QPushButton:pressed#btnRefresh{\n"
"border:3px solid rgb(58, 130, 86);\n"
"}\n"
"\n"
"\n"
"QLabel#labelStatistic{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"}\n"
"\n"
"QLabel#labelLeft{\n"
"background-color: rgba(170, 255, 0,70);\n"
"color:rgb(170, 255, 0);\n"
"}\n"
"\n"
"QLabel:hover#labelLeft{\n"
"color:rgba(170, 255, 0, 180);\n"
"}\n"
"\n"
"QLabel#labelSold{\n"
"color:rgb(170, 255, 0);\n"
"}\n"
"\n"
"QLabel:hover#labelSold{\n"
"color:rgba(170, 255, 0, 180);\n"
"}\n"
"\n"
"QLabel#labelLastSale{\n"
"color:rgb(170, 255, 0);\n"
"background-color: rgba(170, 255, 0,70);\n"
"}\n"
"\n"
"QLabel:hover#labelLastSale{\n"
"color:rgba(170, 255, 0, 180);\n"
"}\n"
"\n"
"QLabel#enterLink{\n"
"color:rgb(170, 255, 0);\n"
"}\n"
"\n"
"QLabel:hover#enterLink{\n"
"color:rgba(170, 255, 0, 180);\n"
"}\n"
"\n"
"QLineEdit#linkLine{\n"
"color: rgb(195, 255, 125);\n"
"    background-color:rgba(194, 255, 124,100);\n"
"border:2px solid rgb(168, 239, 60);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QLineEdit:focus#linkLine{\n"
"border:3px solid rgb(110, 255, 14);\n"
"}\n"
"\n"
"QLineEdit:hover#linkLine{\n"
"border:3px solid rgb(110, 255, 14);\n"
"}\n"
"\n"
"\n"
"QPushButton#btnAddToDB{\n"
"color:rgb(195, 255, 125);\n"
"    background-color: rgb(78, 49, 111);\n"
"border:2px solid rgb(38, 24, 54);\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover#btnAddToDB{\n"
"background-color:rgb(119, 78, 170);\n"
"}\n"
"\n"
"QPushButton:pressed#btnAddToDB{\n"
"border:3px solid rgb(70, 44, 100);\n"
"background-color:rgb(35, 22, 50);\n"
"}\n"
"\n"
"QLabel#successMsg{\n"
"    background-color: rgba(0, 255, 0, 150);\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"}\n"
"\n"
"QLabel:hover#successMsg{\n"
"color: rgb(127, 247, 137);\n"
"}\n"
"\n"
"\n"
"QLabel#unsuccessMsg{\n"
"    background-color: rgba(255, 0, 0, 150);\n"
"    border-top-right-radius:20px;\n"
"    border-top-left-radius:20px;\n"
"}\n"
"\n"
"QLabel:hover#unsuccessMsg{\n"
"color: rgb(197, 78, 74);\n"
"}\n"
"\n"
"QLabel#labelLogin{\n"
"color:rgb(170, 255, 0);\n"
"}\n"
"\n"
"QLabel:hover#labelLogin{\n"
"color:rgba(170, 255, 0, 180);\n"
"}\n"
"\n"
"\n"
"QLabel#labelPass{\n"
"color:rgb(170, 255, 0);\n"
"}\n"
"\n"
"QLabel:hover#labelPass{\n"
"color:rgba(170, 255, 0, 180);\n"
"}\n"
"\n"
"QLineEdit#loginLine{\n"
"color: rgb(195, 255, 125);\n"
"    background-color:rgba(194, 255, 124,100);\n"
"border:2px solid rgb(168, 239, 60);\n"
"border-radius:11px;\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover#loginLine{\n"
"border:3px solid rgb(110, 255, 14);\n"
"}\n"
"\n"
"QLineEdit:focus#loginLine{\n"
"border:3px solid rgb(110, 255, 14);\n"
"}\n"
"\n"
"\n"
"QLineEdit#passLine{\n"
"color: rgb(195, 255, 125);\n"
"    background-color:rgba(194, 255, 124,100);\n"
"border:2px solid rgb(168, 239, 60);\n"
"border-radius:11px;\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover#passLine{\n"
"border:3px solid rgb(110, 255, 14);\n"
"}\n"
"\n"
"QLineEdit:focus#passLine{\n"
"border:3px solid rgb(110, 255, 14);\n"
"}\n"
"\n"
"\n"
"QLabel#rtrn_passLabel{\n"
"color:rgb(170, 255, 0);\n"
"}\n"
"\n"
"QLabel:hover#rtrn_passLabel{\n"
"color:rgba(170, 255, 0, 180);\n"
"}\n"
"\n"
"QLabel#rtrn_linkLabel{\n"
"color:rgb(170, 255, 0);\n"
"}\n"
"\n"
"QLabel:hover#rtrn_linkLabel{\n"
"color:rgba(170, 255, 0, 180);\n"
"}\n"
"\n"
"QLabel#rtrn_loginLabel{\n"
"color:rgb(170, 255, 0);\n"
"}\n"
"\n"
"QLabel:hover#rtrn_loginLabel{\n"
"color:rgba(170, 255, 0, 180);\n"
"}\n"
"\n"
"QLineEdit#rtrn_pass{\n"
"color: rgb(0, 170, 0);\n"
"    background-color:rgba(194, 255, 124,100);\n"
"border:2px solid rgb(168, 239, 60);\n"
"border-radius:8px;\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover#rtrn_pass{\n"
"background-color:rgba(194, 255, 124,60)\n"
"}\n"
"\n"
"QLineEdit#rtrn_login{\n"
"color: rgb(0, 170, 0);\n"
"    background-color:rgba(194, 255, 124,100);\n"
"border:2px solid rgb(168, 239, 60);\n"
"border-radius:8px;\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover#rtrn_login{\n"
"background-color:rgba(194, 255, 124,60)\n"
"}\n"
"\n"
"QLineEdit#rtrn_link{\n"
"color: rgb(0, 170, 0);\n"
"    background-color:rgba(194, 255, 124,100);\n"
"border:2px solid rgb(168, 239, 60);\n"
"border-radius:8px;\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover#rtrn_link{\n"
"background-color:rgba(194, 255, 124,60)\n"
"}\n"
"\n"
"QPushButton#btn_req{\n"
"color:rgb(195, 255, 125);\n"
"    background-color: rgb(78, 49, 111);\n"
"border:2px solid rgb(38, 24, 54);\n"
"border-radius: 14px\n"
"}\n"
"\n"
"QPushButton:hover#btn_req{\n"
"background-color:rgb(119, 78, 170)\n"
"}\n"
"\n"
"QPushButton:pressed#btn_req{\n"
"border:3px solid rgb(70, 44, 100);\n"
"background-color:rgb(35, 22, 50);\n"
"}\n"
"\n"
"QLineEdit#levelLine{\n"
"color: rgb(0, 170, 0);\n"
"    background-color:rgba(194, 255, 124,100);\n"
"border:2px solid rgb(168, 239, 60);\n"
"border-radius:8px;\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover#levelLine{\n"
"background-color:rgba(194, 255, 124,60)\n"
"}\n"
"\n"
"QLineEdit#gamesLine{\n"
"color: rgb(0, 170, 0);\n"
"    background-color:rgba(194, 255, 124,100);\n"
"border:2px solid rgb(168, 239, 60);\n"
"border-radius:8px;\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover#gamesLine{\n"
"background-color:rgba(194, 255, 124,60)\n"
"}\n"
"\n"
"QLabel#level{\n"
"color:rgb(170, 255, 0);\n"
"\n"
"}\n"
"\n"
"QLabel:hover#level{\n"
"color:rgba(170, 255, 0, 180);\n"
"\n"
"}\n"
"\n"
"QLabel#games_count{\n"
"color:rgb(170, 255, 0);\n"
"\n"
"}\n"
"\n"
"QLabel:hover#games_count{\n"
"color:rgba(170, 255, 0, 180);\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton#btn_clear{\n"
"color:rgb(195, 255, 125);\n"
"    background-color: rgb(78, 49, 111);\n"
"border:2px solid rgb(38, 24, 54);\n"
"border-radius: 7px\n"
"}\n"
"\n"
"QPushButton:hover#btn_clear{\n"
"background-color:rgb(119, 78, 170)\n"
"}\n"
"\n"
"QPushButton:pressed#btn_clear{\n"
"border:3px solid rgb(70, 44, 100);\n"
"background-color:rgb(35, 22, 50);\n"
"}\n"
"\n"
"\n"
"QLabel#error_msg{\n"
"background-color: rgb(255, 0, 0);\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"QLabel#pls_wait_msg{\n"
"color: rgb(195, 255, 125);\n"
"}\n"
"\n"
"QLabel:hover#pls_wait_msg{\n"
"color: rgba(195, 255, 125, 150);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(15, 15, 770, 570))
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.topMenu = QtWidgets.QFrame(self.main_frame)
        self.topMenu.setGeometry(QtCore.QRect(0, 0, 771, 50))
        self.topMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenu.setObjectName("topMenu")
        self.seller = QtWidgets.QLabel(self.topMenu)
        self.seller.setGeometry(QtCore.QRect(330, 0, 71, 31))
        self.seller.setMinimumSize(QtCore.QSize(0, 3))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.seller.setFont(font)
        self.seller.setMouseTracking(False)
        self.seller.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seller.setLineWidth(0)
        self.seller.setScaledContents(False)
        self.seller.setAlignment(QtCore.Qt.AlignCenter)
        self.seller.setWordWrap(False)
        self.seller.setIndent(0)
        self.seller.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.seller.setObjectName("seller")
        self.btnClose = QtWidgets.QPushButton(self.topMenu)
        self.btnClose.setGeometry(QtCore.QRect(748, 2, 20, 20))
        self.btnClose.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/close_app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon)
        self.btnClose.setIconSize(QtCore.QSize(28, 30))
        self.btnClose.setObjectName("btnClose")
        self.btnRefresh = QtWidgets.QPushButton(self.topMenu)
        self.btnRefresh.setGeometry(QtCore.QRect(727, 1, 22, 22))
        self.btnRefresh.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/rfrsh_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRefresh.setIcon(icon1)
        self.btnRefresh.setIconSize(QtCore.QSize(18, 18))
        self.btnRefresh.setObjectName("btnRefresh")
        self.version = QtWidgets.QLabel(self.topMenu)
        self.version.setGeometry(QtCore.QRect(10, 20, 70, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.version.setFont(font)
        self.version.setAlignment(QtCore.Qt.AlignCenter)
        self.version.setObjectName("version")
        self.appName = QtWidgets.QLabel(self.topMenu)
        self.appName.setGeometry(QtCore.QRect(0, 4, 160, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.appName.setFont(font)
        self.appName.setAlignment(QtCore.Qt.AlignCenter)
        self.appName.setObjectName("appName")
        self.labelStatistic = QtWidgets.QLabel(self.main_frame)
        self.labelStatistic.setGeometry(QtCore.QRect(40, 70, 691, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.labelStatistic.setFont(font)
        self.labelStatistic.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelStatistic.setIndent(13)
        self.labelStatistic.setObjectName("labelStatistic")
        self.labelLeft = QtWidgets.QLabel(self.main_frame)
        self.labelLeft.setGeometry(QtCore.QRect(40, 140, 691, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelLeft.setFont(font)
        self.labelLeft.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelLeft.setIndent(30)
        self.labelLeft.setObjectName("labelLeft")
        self.labelSold = QtWidgets.QLabel(self.main_frame)
        self.labelSold.setGeometry(QtCore.QRect(540, 145, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelSold.setFont(font)
        self.labelSold.setObjectName("labelSold")
        self.labelLastSale = QtWidgets.QLabel(self.main_frame)
        self.labelLastSale.setGeometry(QtCore.QRect(40, 230, 691, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelLastSale.setFont(font)
        self.labelLastSale.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLastSale.setObjectName("labelLastSale")
        self.rightMenu = QtWidgets.QFrame(self.centralwidget)
        self.rightMenu.setGeometry(QtCore.QRect(745, 65, 40, 520))
        self.rightMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightMenu.setObjectName("rightMenu")
        self.rtrn_linkLabel = QtWidgets.QLabel(self.rightMenu)
        self.rtrn_linkLabel.setGeometry(QtCore.QRect(310, 70, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.rtrn_linkLabel.setFont(font)
        self.rtrn_linkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rtrn_linkLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.rtrn_linkLabel.setObjectName("rtrn_linkLabel")
        self.rtrn_loginLabel = QtWidgets.QLabel(self.rightMenu)
        self.rtrn_loginLabel.setGeometry(QtCore.QRect(191, 142, 100, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.rtrn_loginLabel.setFont(font)
        self.rtrn_loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rtrn_loginLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.rtrn_loginLabel.setObjectName("rtrn_loginLabel")
        self.rtrn_passLabel = QtWidgets.QLabel(self.rightMenu)
        self.rtrn_passLabel.setGeometry(QtCore.QRect(186, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.rtrn_passLabel.setFont(font)
        self.rtrn_passLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rtrn_passLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.rtrn_passLabel.setObjectName("rtrn_passLabel")
        self.btn_req = QtWidgets.QPushButton(self.rightMenu)
        self.btn_req.setGeometry(QtCore.QRect(275, 450, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_req.setFont(font)
        self.btn_req.setObjectName("btn_req")
        self.rtrn_pass = QtWidgets.QLineEdit(self.rightMenu)
        self.rtrn_pass.setGeometry(QtCore.QRect(177, 260, 130, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rtrn_pass.setFont(font)
        self.rtrn_pass.setAlignment(QtCore.Qt.AlignCenter)
        self.rtrn_pass.setObjectName("rtrn_pass")
        self.rtrn_login = QtWidgets.QLineEdit(self.rightMenu)
        self.rtrn_login.setGeometry(QtCore.QRect(177, 170, 130, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rtrn_login.setFont(font)
        self.rtrn_login.setAlignment(QtCore.Qt.AlignCenter)
        self.rtrn_login.setObjectName("rtrn_login")
        self.rtrn_link = QtWidgets.QLineEdit(self.rightMenu)
        self.rtrn_link.setGeometry(QtCore.QRect(100, 100, 531, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rtrn_link.setFont(font)
        self.rtrn_link.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rtrn_link.setObjectName("rtrn_link")
        self.dayz_logo = QtWidgets.QLabel(self.rightMenu)
        self.dayz_logo.setGeometry(QtCore.QRect(110, 304, 61, 31))
        self.dayz_logo.setText("")
        self.dayz_logo.setPixmap(QtGui.QPixmap("icons/dayz_logo.png"))
        self.dayz_logo.setScaledContents(True)
        self.dayz_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.dayz_logo.setIndent(0)
        self.dayz_logo.setObjectName("dayz_logo")
        self.rust_logo = QtWidgets.QLabel(self.rightMenu)
        self.rust_logo.setGeometry(QtCore.QRect(210, 297, 40, 40))
        self.rust_logo.setText("")
        self.rust_logo.setPixmap(QtGui.QPixmap("icons/rust_logo.jpg"))
        self.rust_logo.setScaledContents(True)
        self.rust_logo.setObjectName("rust_logo")
        self.pubg_logo = QtWidgets.QLabel(self.rightMenu)
        self.pubg_logo.setGeometry(QtCore.QRect(280, 300, 65, 37))
        self.pubg_logo.setText("")
        self.pubg_logo.setPixmap(QtGui.QPixmap("icons/pubg_logo.png"))
        self.pubg_logo.setScaledContents(True)
        self.pubg_logo.setObjectName("pubg_logo")
        self.r6_logo = QtWidgets.QLabel(self.rightMenu)
        self.r6_logo.setGeometry(QtCore.QRect(365, 293, 54, 50))
        self.r6_logo.setText("")
        self.r6_logo.setPixmap(QtGui.QPixmap("icons/r6_logo.png"))
        self.r6_logo.setScaledContents(True)
        self.r6_logo.setObjectName("r6_logo")
        self.csgo_logo = QtWidgets.QLabel(self.rightMenu)
        self.csgo_logo.setGeometry(QtCore.QRect(440, 298, 45, 40))
        self.csgo_logo.setText("")
        self.csgo_logo.setPixmap(QtGui.QPixmap("icons/csgo_logo.png"))
        self.csgo_logo.setScaledContents(True)
        self.csgo_logo.setObjectName("csgo_logo")
        self.vac_logo = QtWidgets.QLabel(self.rightMenu)
        self.vac_logo.setGeometry(QtCore.QRect(515, 297, 41, 41))
        self.vac_logo.setText("")
        self.vac_logo.setPixmap(QtGui.QPixmap("icons/vac_logo.png"))
        self.vac_logo.setScaledContents(True)
        self.vac_logo.setObjectName("vac_logo")
        self.levelLine = QtWidgets.QLineEdit(self.rightMenu)
        self.levelLine.setGeometry(QtCore.QRect(410, 170, 130, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.levelLine.setFont(font)
        self.levelLine.setAlignment(QtCore.Qt.AlignCenter)
        self.levelLine.setObjectName("levelLine")
        self.gamesLine = QtWidgets.QLineEdit(self.rightMenu)
        self.gamesLine.setGeometry(QtCore.QRect(410, 260, 130, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.gamesLine.setFont(font)
        self.gamesLine.setAlignment(QtCore.Qt.AlignCenter)
        self.gamesLine.setObjectName("gamesLine")
        self.level = QtWidgets.QLabel(self.rightMenu)
        self.level.setGeometry(QtCore.QRect(430, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.level.setFont(font)
        self.level.setAlignment(QtCore.Qt.AlignCenter)
        self.level.setObjectName("level")
        self.games_count = QtWidgets.QLabel(self.rightMenu)
        self.games_count.setGeometry(QtCore.QRect(420, 230, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setItalic(True)
        self.games_count.setFont(font)
        self.games_count.setAlignment(QtCore.Qt.AlignCenter)
        self.games_count.setObjectName("games_count")
        self.dayz_check = PyToggle(self.rightMenu)
        self.dayz_check.setGeometry(QtCore.QRect(110, 340, 61, 20))
        self.dayz_check.setObjectName("dayz_check")
        self.rust_check = PyToggle(self.rightMenu)
        self.rust_check.setGeometry(QtCore.QRect(200, 340, 51, 21))
        self.rust_check.setObjectName("rust_check")
        self.pubg_check = PyToggle(self.rightMenu)
        self.pubg_check.setGeometry(QtCore.QRect(290, 340, 51, 21))
        self.pubg_check.setObjectName("pubg_check")
        self.r6_check = PyToggle(self.rightMenu)
        self.r6_check.setGeometry(QtCore.QRect(370, 340, 51, 21))
        self.r6_check.setObjectName("r6_check")
        self.csgo_check = PyToggle(self.rightMenu)
        self.csgo_check.setGeometry(QtCore.QRect(440, 350, 41, 21))
        self.csgo_check.setObjectName("csgo_check")
        self.vac_check = PyToggle(self.rightMenu)
        self.vac_check.setGeometry(QtCore.QRect(520, 350, 41, 21))
        self.vac_check.setObjectName("vac_check")
        self.btn_clear = QtWidgets.QPushButton(self.rightMenu)
        self.btn_clear.setGeometry(QtCore.QRect(580, 470, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.error_msg = QtWidgets.QLabel(self.rightMenu)
        self.error_msg.setGeometry(QtCore.QRect(160, 0, 400, 0))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_msg.sizePolicy().hasHeightForWidth())
        self.error_msg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(12)
        self.error_msg.setFont(font)
        self.error_msg.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.error_msg.setToolTipDuration(-1)
        self.error_msg.setAutoFillBackground(False)
        self.error_msg.setLineWidth(0)
        self.error_msg.setMidLineWidth(0)
        self.error_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.error_msg.setWordWrap(False)
        self.error_msg.setObjectName("error_msg")
        self.btnSell = QtWidgets.QPushButton(self.centralwidget)
        self.btnSell.setGeometry(QtCore.QRect(745, 85, 40, 471))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSell.setFont(font)
        self.btnSell.setObjectName("btnSell")
        self.leftMenu = QtWidgets.QFrame(self.centralwidget)
        self.leftMenu.setGeometry(QtCore.QRect(15, 65, 40, 520))
        self.leftMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenu.setObjectName("leftMenu")
        self.btnAdd = QtWidgets.QPushButton(self.leftMenu)
        self.btnAdd.setGeometry(QtCore.QRect(0, 20, 40, 471))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.linkLine = QtWidgets.QLineEdit(self.leftMenu)
        self.linkLine.setGeometry(QtCore.QRect(110, 130, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.linkLine.setFont(font)
        self.linkLine.setObjectName("linkLine")
        self.enterLink = QtWidgets.QLabel(self.leftMenu)
        self.enterLink.setGeometry(QtCore.QRect(220, 90, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.enterLink.setFont(font)
        self.enterLink.setAlignment(QtCore.Qt.AlignCenter)
        self.enterLink.setObjectName("enterLink")
        self.btnAddToDB = QtWidgets.QPushButton(self.leftMenu)
        self.btnAddToDB.setGeometry(QtCore.QRect(280, 340, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnAddToDB.setFont(font)
        self.btnAddToDB.setObjectName("btnAddToDB")
        self.successMsg = QtWidgets.QLabel(self.leftMenu)
        self.successMsg.setGeometry(QtCore.QRect(120, 520, 510, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setItalic(True)
        font.setUnderline(True)
        self.successMsg.setFont(font)
        self.successMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.successMsg.setObjectName("successMsg")
        self.unsuccessMsg = QtWidgets.QLabel(self.leftMenu)
        self.unsuccessMsg.setGeometry(QtCore.QRect(170, 520, 421, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setItalic(False)
        font.setUnderline(True)
        self.unsuccessMsg.setFont(font)
        self.unsuccessMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.unsuccessMsg.setObjectName("unsuccessMsg")
        self.loginLine = QtWidgets.QLineEdit(self.leftMenu)
        self.loginLine.setGeometry(QtCore.QRect(280, 200, 180, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.loginLine.setFont(font)
        self.loginLine.setObjectName("loginLine")
        self.passLine = QtWidgets.QLineEdit(self.leftMenu)
        self.passLine.setGeometry(QtCore.QRect(280, 266, 180, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.passLine.setFont(font)
        self.passLine.setObjectName("passLine")
        self.labelLogin = QtWidgets.QLabel(self.leftMenu)
        self.labelLogin.setGeometry(QtCore.QRect(326, 165, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.labelLogin.setFont(font)
        self.labelLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogin.setObjectName("labelLogin")
        self.labelPass = QtWidgets.QLabel(self.leftMenu)
        self.labelPass.setGeometry(QtCore.QRect(324, 233, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.labelPass.setFont(font)
        self.labelPass.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPass.setObjectName("labelPass")
        self.pls_wait_msg = QtWidgets.QLabel(self.leftMenu)
        self.pls_wait_msg.setGeometry(QtCore.QRect(310, 380, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pls_wait_msg.setFont(font)
        self.pls_wait_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.pls_wait_msg.setObjectName("pls_wait_msg")
        self.main_frame.raise_()
        self.rightMenu.raise_()
        self.leftMenu.raise_()
        self.btnSell.raise_()
        handler.setCentralWidget(self.centralwidget)

        self.retranslateUi(handler)
        QtCore.QMetaObject.connectSlotsByName(handler)

    def retranslateUi(self, handler):
        _translate = QtCore.QCoreApplication.translate
        handler.setWindowTitle(_translate("handler", "MainWindow"))
        self.seller.setText(_translate("handler", "LOGIN"))
        self.version.setText(_translate("handler", "version: 0.0.1"))
        self.appName.setText(_translate("handler", "<strong>ACCOUNT </strong> HANDLER"))
        self.labelStatistic.setText(_translate("handler", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">info</span><span style=\" font-size:28pt;\">:</span></p></body></html>"))
        self.labelLeft.setText(_translate("handler", "Accounts left:"))
        self.labelSold.setText(_translate("handler", "Accounts sold:"))
        self.labelLastSale.setText(_translate("handler", "Last sale was at:"))
        self.rtrn_linkLabel.setText(_translate("handler", "link"))
        self.rtrn_loginLabel.setText(_translate("handler", "login"))
        self.rtrn_passLabel.setText(_translate("handler", "password"))
        self.btn_req.setText(_translate("handler", "REQUEST"))
        self.level.setText(_translate("handler", "level"))
        self.games_count.setText(_translate("handler", "games"))
        self.btn_clear.setText(_translate("handler", "CLEAR"))
        self.error_msg.setText(_translate("handler", "<strong>ERROR</strong>"))
        self.btnSell.setText(_translate("handler", "SELL"))
        self.btnAdd.setText(_translate("handler", "ADD"))
        self.enterLink.setText(_translate("handler", "Enter link"))
        self.btnAddToDB.setText(_translate("handler", "ADD TO DATA BASE"))
        self.successMsg.setText(_translate("handler", "Account was successfully added to data base!"))
        self.unsuccessMsg.setText(_translate("handler", "Account wasn\'t added to data base!"))
        self.labelLogin.setText(_translate("handler", "login"))
        self.labelPass.setText(_translate("handler", "password"))
        self.pls_wait_msg.setText(_translate("handler", "Please, wait..."))
from pytoggle import PyToggle


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    handler = QtWidgets.QMainWindow()
    ui = Ui_handler()
    ui.setupUi(handler)
    handler.show()
    sys.exit(app.exec_())
